// This file is generated by Slice Machine. Update with care!

import Card from './Card';
import Landscape from './Landscape';

export {
	Card,
	Landscape,
};

export const components = {
	card: Card,
	landscape: Landscape,
};
